### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by jelflein** [raphaelhanneken/apple-juice#1]
Hello,

I like your app. It is the best battery app ❤️. When I plug in my power adapter, the battery icon will need 5sec to update the symbol, but the system battery needs no update time.

P.s.

I added your battery app by Homebrew Cask

`brew cask install apple-juice`

https://brew.sh
https://caskroom.github.io

**Comment by raphaelhanneken** [comment]
Hi @jelflein  
Thank you very much for using Apple Juice! I'm ecstatic you like it. 👍
Unfortunately, I have little time at the moment. Therefore I don't know yet when I'll be able to look into this issue.
But I'll write, whenever I'll get to it.

**Comment by jelflein** [comment]
I recorded a video. I think the bug is not in the notification, but he is in charing attribute.

https://vid.me/m7phy

**Comment by raphaelhanneken** [comment]
Hey @jelflein unfortunately I can't reproduce your issue, therefore I have no clue whats going wrong. I will leave this issue open, maybe someone else has the same problem and a solution for it, but at the moment I can't really help you.

**Comment by raphaelhanneken** [comment]
Closed due to inactivity.

**Comment by camlloyd** [comment]
FWIW, I also have the same issue.
