### ISSUE TITLE
Add support for Mojave Dark Mode in the Notification Center

### ISSUE THREAD

**Issue by oddharsh** [raphaelhanneken/apple-juice#12]
As of now, it seems that the notification center panel stays in the "light" theme regardless of system settings, and I think that having it change would make it look more integrated/stock.

**Comment by raphaelhanneken** [comment]
Hi @oddharsh, thanks a lot für reporting this. This is definitely a bug, I will look into this. 👍

**Comment by raphaelhanneken** [comment]
Should be fixed in v1.7.1
