### ISSUE TITLE
Wrong download url in upcast.xml

### ISSUE THREAD

**Issue by suschizu** [raphaelhanneken/apple-juice#14]
Hello! I've noticed that the url in the appcast (https://raphaelhanneken.github.io/apple-juice/sparkle/appcast.xml) isn't working for v 1.8.1:
url="https://github.com/raphaelhanneken/apple-juice/releases/download/1.8.1/Apple.Juice.zip"
shouldn't it be a .dmg?

**Comment by raphaelhanneken** [comment]
Hi @suschizu! Thanks! You're right, it should be a dmg file. I were trying something, because the updater seems to be broken. I've changed the appcast url, hopefully the update will work now.

**Comment by suschizu** [comment]
Great - Thank you :)
