### ISSUE TITLE
Bring to Front - About Apple Juice

### ISSUE THREAD

**Issue by camlloyd** [raphaelhanneken/apple-juice#15]
Consider bringing the ```About Apple Juice``` window to the front. 
Although it is not intrusive, it does hide behind other open windows.

**Comment by raphaelhanneken** [comment]
As Apple Juice is a menu bar application it doesn't get focus, from the window server. Therefore orderFront will always display the window behind the application, which is currently focused. As the benefits doesn't really justify the efforts required I won't fix this. But feel free to create a pr, if you want.
