### ISSUE TITLE
'%' should not have preceding space

### ISSUE THREAD

**Issue by mayankk2308** [raphaelhanneken/apple-juice#17]
Minor gripe, but in Apple's default battery icon, there is no space preceding the % sign. Example: **87%** and not **87 %**. Would be great if the app could conform to this.

**Comment by camlloyd** [comment]
@mayankk2308 I've removed the space in my local version, but this looks to be a localisation thing. 

In German, there is a space preceding the % sign on macOS. 
In English (UK), there is no preceding space.

@raphaelhanneken, would it be possible to implement whether whitespace precedes the % sign or not based on preferred language (like in macOS)? You already have ```Localizable.strings```...

Thanks!

**Comment by raphaelhanneken** [comment]
Apple Juice v1.9.0 now uses NumberFormatter to localise the percentage. Thanks for reporting this 👍

**Comment by camlloyd** [comment]
For completeness, is it possible to implement this for the notification percentages also?

**Comment by raphaelhanneken** [comment]
Oops... of course. I forgot about the notifications - I'll adjust the texts asap. 😅

**Comment by raphaelhanneken** [comment]
Notification percentages should be localised too, with v1.10.0.

**Comment by camlloyd** [comment]
> Notification percentages should be localised too, with v1.10.0.
@raphaelhanneken does this affect the percentages in the _Notifications_ submenu?
