### ISSUE TITLE
Displays 99% At Full Charge

### ISSUE THREAD

**Issue by Jackson-S** [raphaelhanneken/apple-juice#3]
<img width="238" alt="screen shot 2018-04-25 at 12 25 35 pm" src="https://user-images.githubusercontent.com/19158781/39223197-f433de5c-4883-11e8-963c-ec92a97d4791.png">
While the charge should be displaying 100% I think there's a floating point or logic error stopping it from displaying correctly.

Device: Macbook Pro 15in Late 2016
OS: 10.13.4 (17E199)

**Comment by raphaelhanneken** [comment]
Hi @Jackson-S!
It seems like the estimate for the current mAh value is wrong. Does the percentage remain at 99%, for a very long time (over 5 minutes)?

**Comment by Jackson-S** [comment]
It remains that way indefinitely, but corrects its self if I either change power sources or restart the program. 
I've done some further testing and ioreg reports "FullyCharged" as true, but the program doesn't check this state value when charging, only when initialising or changing states.

**Comment by raphaelhanneken** [comment]
It's because Apple Juice doesn't poll for changes, but gets notified by the OS whenever something (mAh, power source, etc) changes. That way, when there are no changes to the power source no unnecessary updates are triggered. 

The next time you have this issue, could you please run this command `pmset -g batt | grep -E "\d+"` and post the output here?

**Comment by Jackson-S** [comment]
`$ pmset -g batt | grep -E "\d+"`
 -InternalBattery-0 (id=3866723)	100%; charged; 0:00 remaining present: true

**Comment by raphaelhanneken** [comment]
I've just released a new version, which uses another method of getting the percentage from the system. I hope this fixes the issue.

**Comment by Jackson-S** [comment]
This seems to have fixed the issue perfectly.
