### ISSUE TITLE
Does not work with Mac desktop 

### ISSUE THREAD

**Issue by pkasson** [raphaelhanneken/apple-juice#4]
Want to have this work for my desktop, and detect when on UPS / battery, it appears in menu bar, but has X over battery and does not run.

**Comment by raphaelhanneken** [comment]
I haven't developed Apple Juice with desktops in mind. Therefore it's not capable of detecting external power sources and I'm not sure what it would take to implement this feature. Sadly, I currently don't have the time to make big updates like this. But feel free to fork the project and implement it yourself.
