### ISSUE TITLE
Add "Launch at login" setting

### ISSUE THREAD

**Issue by thefabbulus** [raphaelhanneken/apple-juice#7]
I think a "Launch at login" toggle/checkbox would be useful, since now the user can only achieve that by manually adding it in System settings.

@raphaelhanneken let me know what do you think about that feature, and I could give it a look.

**Comment by raphaelhanneken** [comment]
Hi @fabersky! That would be great! I've implemented a Launch at Login toggle for [Espresso](https://github.com/raphaelhanneken/espresso) but never bothered to add it to Apple Juice too.

**Comment by BlakeTNC** [comment]
Has this been implemented? I son't see it in the latest version.

**Comment by raphaelhanneken** [comment]
Hi @BlakeTNC,
this feature were implemented, but I had to remove it because it was causing problems with Gatekeeper. See issue #18

**Comment by BlakeTNC** [comment]
Hi @raphaelhanneken. I see, thats too bad. Well, I imagine the majority of people would need your app to be launched at login, to be generally useful to them. And many people don't know how to do this manually. I have two potential suggestions I can think of. 

1) Add a menu item (possibly in "preferences"), called "Launch at login instructions". It would show a dialog, saying something like:
"To launch this program at login, open System Preferences>Users & Groups>Login Items. 
Add this program to the 'Login Items' list. After that, this program will start at launch." 
(If desired, you could include a screenshot of the relevant system preference page for extra clarity.) 

OR

2) Find out how other open source programs are accomplishing this successfully. One program that does this is Syncthing.  https://github.com/syncthing/syncthing-macos 
This other utility also looks promising: (https://github.com/Teamwork/node-auto-launch#mac), they have put a lot of research into how to programmatically enable autolaunch for mac apps, and even into how to get them authorized for the mac store if that was ever a goal.

-Blake

**Comment by raphaelhanneken** [comment]
Thanks for your research @BlakeTNC I will take a look at it, in the next days.

**Comment by brightly-salty** [comment]
I'd like to second the need for this feature, make sure its still open, and add a potential [example of source code from Rectangle](https://github.com/rxhanson/Rectangle/search?q=launch+on+login&unscoped_q=launch+on+login).

**Comment by raphaelhanneken** [comment]
Feature was added with v2020.11.
